spring:
  application:
    name: eagle-bank-api
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/eagle-bank
          jwk-set-uri: http://localhost:8180/realms/eagle-bank/protocol/openid-connect/certs

# SpringDoc OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    filter: true
    operations-sorter: alpha
    tags-sorter: alpha
    oauth:
      client-id: eagle-bank-api
      use-pkce-with-authorization-code-grant: false
  show-actuator: false
  server:
    url: http://localhost:8080/eagle-bank

keycloak:
  auth-server-url: http://localhost:8180
  realm: eagle-bank

# Security Configuration
security:
  rate-limit:
    default:
      requests-per-minute: 100
      burst-capacity: 20
    strict:
      requests-per-minute: 20
      burst-capacity: 5
    relaxed:
      requests-per-minute: 200
      burst-capacity: 50

server:
  port: 8080
  servlet:
    context-path: /eagle-bank

# Eagle Bank specific configuration
eagle-bank:
  bank-account:
    default-sort-code: "10-10-10"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging Configuration (now handled by logback-spring.xml)
# Enhanced structured logging with correlation IDs and performance monitoring 