spring:
  datasource:
    url: jdbc:postgresql://eagle-bank-postgres:5432/eagle_bank
    driver-class-name: org.postgresql.Driver
    username: eagle_user
    password: eagle_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://eagle-bank-keycloak:8180/realms/eagle-bank
          jwk-set-uri: http://eagle-bank-keycloak:8180/realms/eagle-bank/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://eagle-bank-keycloak:8180
  realm: eagle-bank
  resource: eagle-bank-api
  public-client: true
  principal-attribute: preferred_username

# Eagle Bank specific configuration for development
eagle-bank:
  bank-account:
    default-sort-code: "12-34-56"  # Different sort code for dev environment

logging:
  level:
    com.eaglebank: DEBUG
    org.springframework.security: DEBUG
    org.keycloak: DEBUG 