apiVersion: apps/v1
kind: Deployment
metadata:
  name: eagle-bank-api
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: eagle-bank-api
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
        - name: LOGGING_LEVEL_COM_EAGLEBANK
          value: "DEBUG"
