apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: eagle-bank-staging

namespace: staging

resources:
  - ../base

namePrefix: staging-

commonLabels:
  environment: staging

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml

configMapGenerator:
  - name: eagle-bank-config-staging
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=staging
      - LOGGING_LEVEL_COM_EAGLEBANK=DEBUG
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always

images:
  - name: ghcr.io/harish516/eagle-bank-api-java
    newTag: ${IMAGE_TAG}
