apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eagle-bank-api
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "1000"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
spec:
  tls:
  - hosts:
    - api.eaglebank.com
    secretName: eagle-bank-api-tls-prod
  rules:
  - host: api.eaglebank.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eagle-bank-api
            port:
              number: 80
