apiVersion: v1
kind: ConfigMap
metadata:
  name: eagle-bank-config
  namespace: eagle-bank
  labels:
    app.kubernetes.io/name: eagle-bank-api
    app.kubernetes.io/component: config
data:
  # Application Configuration
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  
  # Database Configuration
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/eagle_bank"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  
  # Redis Configuration
  SPRING_REDIS_HOST: "redis-service"
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_TIMEOUT: "2000ms"
  SPRING_REDIS_LETTUCE_POOL_MAX_ACTIVE: "20"
  SPRING_REDIS_LETTUCE_POOL_MAX_IDLE: "10"
  SPRING_REDIS_LETTUCE_POOL_MIN_IDLE: "5"
  
  # HikariCP Configuration
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "50"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "10"
  SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: "300000"
  SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: "1800000"
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "30000"
  
  # Actuator Configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,metrics,prometheus,info"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  
  # Security Configuration
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak-service:8080/realms/eagle-bank"
  
  # Logging Configuration
  LOGGING_LEVEL_COM_EAGLEBANK: "INFO"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: "INFO"
  LOGGING_PATTERN_CONSOLE: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  
  # JVM Configuration
  JAVA_OPTS: "-Xmx1024m -Xms512m -XX:+UseG1GC -XX:+UseStringDeduplication"

---
apiVersion: v1
kind: Secret
metadata:
  name: eagle-bank-secrets
  namespace: eagle-bank
  labels:
    app.kubernetes.io/name: eagle-bank-api
    app.kubernetes.io/component: secret
type: Opaque
data:
  # Base64 encoded secrets - these should be properly encrypted in production
  SPRING_DATASOURCE_USERNAME: ZWFnbGVfdXNlcg== # eagle_user
  SPRING_DATASOURCE_PASSWORD: ZWFnbGVfcGFzc3dvcmQ= # eagle_password
  SPRING_REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ= # redis_password
