apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: eagle-bank
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: cache
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      serviceAccountName: redis-sa
      containers:
      - name: redis
        image: redis:7.2-alpine
        ports:
        - name: redis
          containerPort: 6379
        command:
        - redis-server
        - /etc/redis/redis.conf
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
      - name: redis-data
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: eagle-bank
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache-service
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app.kubernetes.io/name: redis

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: eagle-bank
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: config
data:
  redis.conf: |
    # Network and Security
    bind 0.0.0.0
    port 6379
    requirepass ${REDIS_PASSWORD}
    
    # Memory Management
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    
    # Persistence
    save 900 1
    save 300 10
    save 60 10000
    
    # Logging
    loglevel notice
    
    # Performance
    tcp-keepalive 300
    timeout 0

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: eagle-bank
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: secret
type: Opaque
data:
  password: cmVkaXNfcGFzc3dvcmQ= # redis_password

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: eagle-bank
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: false
