apiVersion: v1
kind: Service
metadata:
  name: eagle-bank-api
  namespace: eagle-bank
  labels:
    app.kubernetes.io/name: eagle-bank-api
    app.kubernetes.io/component: service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: actuator
    port: 8080
    targetPort: actuator
    protocol: TCP
  selector:
    app.kubernetes.io/name: eagle-bank-api

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eagle-bank-api
  namespace: eagle-bank
  labels:
    app.kubernetes.io/name: eagle-bank-api
    app.kubernetes.io/component: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.eaglebank.com
    secretName: eagle-bank-api-tls
  rules:
  - host: api.eaglebank.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: eagle-bank-api
            port:
              number: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eagle-bank-api
  namespace: eagle-bank
  labels:
    app.kubernetes.io/name: eagle-bank-api
    app.kubernetes.io/component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eagle-bank-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
